
title: Saket Sonekar
url: 'https://www.linkedin.com/in/saket-sonekar-68266299/'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Saket Sonekar  ## put your name
title: 'Product Manager | Operations Expertise | Human Maps & Driverless Vehicles Maps'  ## your title
location: Hyderabad, India


## Social Profiles
linkedin: https://www.linkedin.com/in/saket-sonekar-68266299/  ## your linkedin account url
instagram: https://www.instagram.com/culturednomad_/  ## you instagram account url
email: mailto:sakets@hotmail.com



# Update all the sections by editing the files inside _includes folder.
